#!/bin/bash

# Activate the virtual environment.
. env/bin/activate

# Install packages for then environment.
pip3 install -r requirements

# Install the MacroPad helper library.
circup install adafruit_macropad

# Install the LED animation library.
circup install adafruit_led_animation

# Update existing bundles on the board.
circup update

# Copy the code into the board.
# This is assuming your board is mounted on /media/
cp *.py components/*.py *.json fonts/*.pcf /media/$(whoami)/CIRCUITPY/

# Deactivate environment.
deactivate