GLYPH_KEYS = {
    'activitypub': '\uf2f2',
    'address book o': '\uf2ba',
    'address book': '\uf2b9',
    'address card o': '\uf2bc',
    'address card': '\uf2bb',
    'adjust': '\uf042',
    'adn': '\uf170',
    'align center': '\uf037',
    'align justify': '\uf039',
    'align left': '\uf036',
    'align right': '\uf038',
    'amazon': '\uf270',
    'ambulance': '\uf0f9',
    'american sign language interpreting': '\uf2a3',
    'anchor': '\uf13d',
    'android': '\uf17b',
    'angellist': '\uf209',
    'angle double down': '\uf103',
    'angle double left': '\uf100',
    'angle double right': '\uf101',
    'angle double up': '\uf102',
    'angle down': '\uf107',
    'angle left': '\uf104',
    'angle right': '\uf105',
    'angle up': '\uf106',
    'apple': '\uf179',
    'archive org': '\uf2fc',
    'archive': '\uf187',
    'archlinux': '\uf323',
    'area chart': '\uf1fe',
    'arrow circle down': '\uf0ab',
    'arrow circle left': '\uf0a8',
    'arrow circle o down': '\uf01a',
    'arrow circle o left': '\uf190',
    'arrow circle o right': '\uf18e',
    'arrow circle o up': '\uf01b',
    'arrow circle right': '\uf0a9',
    'arrow circle up': '\uf0aa',
    'arrow down': '\uf063',
    'arrow left': '\uf060',
    'arrow right': '\uf061',
    'arrows alt': '\uf0b2',
    'arrows h': '\uf07e',
    'arrows': '\uf047',
    'arrows v': '\uf07d',
    'arrow up': '\uf062',
    'artstation': '\uf2ed',
    'askfm': '\uf33a',
    'assistive listening systems': '\uf2a2',
    'asterisk': '\uf069',
    'att': '\uf31e',
    'at': '\uf1fa',
    'audio description': '\uf29e',
    'backward': '\uf04a',
    'balance scale': '\uf24e',
    'bandcamp': '\uf2d5',
    'ban': '\uf05e',
    'bar chart': '\uf080',
    'barcode': '\uf02a',
    'bars': '\uf0c9',
    'bath': '\uf2cd',
    'battery empty': '\uf244',
    'battery full': '\uf240',
    'battery half': '\uf242',
    'battery quarter': '\uf243',
    'battery three quarters': '\uf241',
    'bed': '\uf236',
    'beer': '\uf0fc',
    'behance square': '\uf1b5',
    'behance': '\uf1b4',
    'bell o': '\uf0f3',
    'bell ringing o': '\uf330',
    'bell ringing': '\uf32d',
    'bell slash o': '\uf1f7',
    'bell slash': '\uf1f6',
    'bell': '\uf0a2',
    'bicycle': '\uf206',
    'binoculars': '\uf1e5',
    'biometric': '\uf32b',
    'birthday cake': '\uf1fd',
    'bitbucket square': '\uf172',
    'bitbucket': '\uf171',
    'black tie': '\uf27e',
    'blind': '\uf29d',
    'blockstack': '\uf33b',
    'bluetooth b': '\uf294',
    'bluetooth': '\uf293',
    'boardgamegeek': '\uf33c',
    'bold': '\uf032',
    'bolt': '\uf0e7',
    'bomb': '\uf1e2',
    'bookmark o': '\uf097',
    'bookmark': '\uf02e',
    'book': '\uf02d',
    'bootstrap': '\uf315',
    'braille': '\uf2a1',
    'briefcase': '\uf0b1',
    'btc': '\uf15a',
    'bug': '\uf188',
    'building o': '\uf0f7',
    'building': '\uf1ad',
    'bullhorn': '\uf0a1',
    'bullseye': '\uf140',
    'bunny': '\uf35f',
    'bus': '\uf207',
    'buymeacoffee': '\uf33d',
    'buysellads': '\uf20d',
    'calculator': '\uf1ec',
    'calendar check o': '\uf274',
    'calendar minus o': '\uf272',
    'calendar o': '\uf133',
    'calendar plus o': '\uf271',
    'calendar times o': '\uf273',
    'calendar': '\uf073',
    'camera retro': '\uf083',
    'camera': '\uf030',
    'caret down': '\uf0d7',
    'caret left': '\uf0d9',
    'caret right': '\uf0da',
    'caret square o down': '\uf150',
    'caret square o left': '\uf191',
    'caret square o right': '\uf152',
    'caret square o up': '\uf151',
    'caret up': '\uf0d8',
    'cart arrow down': '\uf218',
    'cart plus': '\uf217',
    'car': '\uf1b9',
    'cc amex': '\uf1f3',
    'cc by': '\uf33e',
    'cc cc': '\uf33f',
    'cc diners club': '\uf24c',
    'cc discover': '\uf1f2',
    'cc jcb': '\uf24b',
    'cc mastercard': '\uf1f1',
    'cc nc eu': '\uf341',
    'cc nc jp': '\uf342',
    'cc nc': '\uf340',
    'cc nd': '\uf343',
    'cc paypal': '\uf1f4',
    'cc pd': '\uf344',
    'cc remix': '\uf345',
    'cc sa': '\uf346',
    'cc share': '\uf347',
    'cc stripe': '\uf1f5',
    'cc': '\uf20a',
    'cc visa': '\uf1f0',
    'cc zero': '\uf348',
    'certificate': '\uf0a3',
    'chain broken': '\uf127',
    'check circle o': '\uf05d',
    'check circle': '\uf058',
    'check square o': '\uf046',
    'check square': '\uf14a',
    'check': '\uf00c',
    'chevron circle down': '\uf13a',
    'chevron circle left': '\uf137',
    'chevron circle right': '\uf138',
    'chevron circle up': '\uf139',
    'chevron down': '\uf078',
    'chevron left': '\uf053',
    'chevron right': '\uf054',
    'chevron up': '\uf077',
    'child': '\uf1ae',
    'chrome': '\uf268',
    'circle o notch': '\uf1ce',
    'circle o': '\uf10c',
    'circle thin': '\uf1db',
    'circle': '\uf111',
    'classicpress circle': '\uf332',
    'classicpress': '\uf331',
    'clipboard': '\uf0ea',
    'clock o': '\uf017',
    'clone': '\uf24d',
    'cloud download': '\uf0ed',
    'cloud': '\uf0c2',
    'cloud upload': '\uf0ee',
    'code fork': '\uf126',
    'codepen': '\uf1cb',
    'code': '\uf121',
    'codiepie': '\uf284',
    'coffee': '\uf0f4',
    'cogs': '\uf085',
    'cog': '\uf013',
    'columns': '\uf0db',
    'commenting o': '\uf27b',
    'commenting': '\uf27a',
    'comment o': '\uf0e5',
    'comments o': '\uf0e6',
    'comments': '\uf086',
    'comment': '\uf075',
    'compass': '\uf14e',
    'compress': '\uf066',
    'connectdevelop': '\uf20e',
    'contao': '\uf26d',
    'conway glider': '\uf349',
    'copyright': '\uf1f9',
    'creative commons': '\uf25e',
    'credit card alt': '\uf283',
    'credit card': '\uf09d',
    'crop': '\uf125',
    'crosshairs': '\uf05b',
    'csharp': '\uf34a',
    'css3': '\uf13c',
    'cubes': '\uf1b3',
    'cube': '\uf1b2',
    'c': '\uf31c',
    'cutlery': '\uf0f5',
    'dashcube': '\uf210',
    'database': '\uf1c0',
    'deaf': '\uf2a4',
    'debian': '\uf2ff',
    'delicious': '\uf1a5',
    'desktop': '\uf108',
    'deviantart': '\uf1bd',
    'dev to': '\uf316',
    'diamond': '\uf219',
    'diaspora': '\uf2e5',
    'digg': '\uf1a6',
    'digitalocean': '\uf31d',
    'discord alt': '\uf2ef',
    'discord': '\uf2ee',
    'dogmazic': '\uf303',
    'dot circle o': '\uf192',
    'download': '\uf019',
    'dribbble': '\uf17d',
    'dropbox': '\uf16b',
    'drupal': '\uf1a9',
    'edge': '\uf282',
    'eercast': '\uf2da',
    'eject': '\uf052',
    'ellipsis h': '\uf141',
    'ellipsis v': '\uf142',
    'email bulk o': '\uf34c',
    'email bulk': '\uf34b',
    'emby': '\uf319',
    'empire': '\uf1d1',
    'envelope open o': '\uf2b7',
    'envelope open': '\uf2b6',
    'envelope o': '\uf003',
    'envelope square': '\uf199',
    'envelope': '\uf0e0',
    'envira': '\uf299',
    'eraser': '\uf12d',
    'ethereum': '\uf2f3',
    'etsy': '\uf2d7',
    'eur': '\uf153',
    'exchange': '\uf0ec',
    'exclamation circle': '\uf06a',
    'exclamation triangle': '\uf071',
    'exclamation': '\uf12a',
    'expand': '\uf065',
    'expeditedssl': '\uf23e',
    'external link square': '\uf14c',
    'external link': '\uf08e',
    'eyedropper': '\uf1fb',
    'eye slash': '\uf070',
    'eye': '\uf06e',
    'facebook messenger': '\uf2fe',
    'facebook official': '\uf230',
    'facebook square': '\uf082',
    'facebook': '\uf09a',
    'fast backward': '\uf049',
    'fast forward': '\uf050',
    'fax': '\uf1ac',
    'f droid': '\uf32a',
    'female': '\uf182',
    'ffmpeg': '\uf30f',
    'fighter jet': '\uf0fb',
    'file archive o': '\uf1c6',
    'file audio o': '\uf1c7',
    'file code o': '\uf1c9',
    'file epub': '\uf321',
    'file excel o': '\uf1c3',
    'file image o': '\uf1c5',
    'file o': '\uf016',
    'file pdf o': '\uf1c1',
    'file powerpoint o': '\uf1c4',
    'files o': '\uf0c5',
    'file text o': '\uf0f6',
    'file text': '\uf15c',
    'file ': '\uf15b',
    'file video o': '\uf1c8',
    'file word o': '\uf1c2',
    'film': '\uf008',
    'filter ': '\uf0b0',
    'fire extinguisher': '\uf134',
    'firefox': '\uf269',
    'fire': '\uf06d',
    'first order': '\uf2b0',
    'fivehundredpx': '\uf26e',
    'flag checkered': '\uf11e',
    'flag o': '\uf11d',
    'flag': '\uf024',
    'flask': '\uf0c3',
    'flickr': '\uf16e',
    'floppy o': '\uf0c7',
    'folder open o': '\uf115',
    'folder open': '\uf07c',
    'folder o': '\uf114',
    'folder': '\uf07b',
    'font awesome': '\uf2b4',
    'fonticons': '\uf280',
    'font': '\uf031',
    'fork awesome': '\uf2e3',
    'fort awesome': '\uf286',
    'forumbee': '\uf211',
    'forward': '\uf04e',
    'foursquare': '\uf180',
    'free code camp': '\uf2c5',
    'freedombox': '\uf2fd',
    'friendica': '\uf2e6',
    'frown o': '\uf119',
    'funkwhale': '\uf339',
    'futbol o': '\uf1e3',
    'gamepad': '\uf11b',
    'gavel': '\uf0e3',
    'gbp': '\uf154',
    'genderless': '\uf22d',
    'get pocket': '\uf265',
    'gg circle': '\uf261',
    'gg': '\uf260',
    'gift': '\uf06b',
    'gimp': '\uf31b',
    'gitea': '\uf31f',
    'github alt': '\uf113',
    'github square': '\uf092',
    'github': '\uf09b',
    'gitlab': '\uf296',
    'git square': '\uf1d2',
    'git': '\uf1d3',
    'glass': '\uf000',
    'glide g': '\uf2a6',
    'glide': '\uf2a5',
    'globe e': '\uf304',
    'globe': '\uf0ac',
    'globe w': '\uf305',
    'gnupg': '\uf30d',
    'gnu social': '\uf2e7',
    'gnu': '\uf34d',
    'google play': '\uf34e',
    'google plus official': '\uf2b3',
    'google plus square': '\uf0d4',
    'google plus': '\uf0d5',
    'google': '\uf1a0',
    'google wallet': '\uf1ee',
    'graduation cap': '\uf19d',
    'gratipay': '\uf184',
    'grav': '\uf2d6',
    'hackaday': '\uf30a',
    'hacker news': '\uf1d4',
    'hackster': '\uf326',
    'hal': '\uf333',
    'hand lizard o': '\uf258',
    'hand o down': '\uf0a7',
    'hand o left': '\uf0a5',
    'hand o right': '\uf0a4',
    'hand o up': '\uf0a6',
    'hand paper o': '\uf256',
    'hand peace o': '\uf25b',
    'hand pointer o': '\uf25a',
    'hand rock o': '\uf255',
    'hand scissors o': '\uf257',
    'handshake o': '\uf2b5',
    'hand spock o': '\uf259',
    'hashnode': '\uf317',
    'hashtag': '\uf292',
    'hdd o': '\uf0a0',
    'header': '\uf1dc',
    'headphones': '\uf025',
    'heartbeat': '\uf21e',
    'heart o': '\uf08a',
    'heart': '\uf004',
    'heroku': '\uf34f',
    'history': '\uf1da',
    'home assistant': '\uf350',
    'home': '\uf015',
    'hospital o': '\uf0f8',
    'hourglass end': '\uf253',
    'hourglass half': '\uf252',
    'hourglass o': '\uf250',
    'hourglass start': '\uf251',
    'hourglass': '\uf254',
    'houzz': '\uf27c',
    'h square': '\uf0fd',
    'html5': '\uf13b',
    'hubzilla': '\uf2eb',
    'i cursor': '\uf246',
    'id badge': '\uf2c1',
    'id card o': '\uf2c3',
    'id card': '\uf2c2',
    'ils': '\uf20b',
    'imdb': '\uf2d8',
    'inbox': '\uf01c',
    'indent': '\uf03c',
    'industry': '\uf275',
    'info circle': '\uf05a',
    'info': '\uf129',
    'inkscape': '\uf312',
    'inr': '\uf156',
    'instagram': '\uf16d',
    'internet explorer': '\uf26b',
    'ioxhost': '\uf208',
    'italic': '\uf033',
    'java': '\uf351',
    'jirafeau': '\uf318',
    'joomla': '\uf1aa',
    'joplin': '\uf310',
    'jpy': '\uf157',
    'jsfiddle': '\uf1cc',
    'julia': '\uf334',
    'jupyter': '\uf335',
    'keybase': '\uf2f4',
    'keyboard o': '\uf11c',
    'key modern': '\uf2f7',
    'key': '\uf084',
    'krw': '\uf159',
    'language': '\uf1ab',
    'laptop': '\uf109',
    'laravel': '\uf30b',
    'lastfm square': '\uf203',
    'lastfm': '\uf202',
    'leaf': '\uf06c',
    'leanpub': '\uf212',
    'lemon o': '\uf094',
    'level down': '\uf149',
    'level up': '\uf148',
    'liberapay square': '\uf2e8',
    'liberapay': '\uf2e9',
    'life ring': '\uf1cd',
    'lightbulb o': '\uf0eb',
    'line chart': '\uf201',
    'linkedin square': '\uf08c',
    'linkedin': '\uf0e1',
    'link': '\uf0c1',
    'linode': '\uf2b8',
    'linux': '\uf17c',
    'list alt': '\uf022',
    'list ol': '\uf0cb',
    'list ': '\uf03a',
    'list ul': '\uf0ca',
    'location arrow': '\uf124',
    'lock': '\uf023',
    'long arrow down': '\uf175',
    'long arrow left': '\uf177',
    'long arrow right': '\uf178',
    'long arrow up': '\uf176',
    'low vision': '\uf2a8',
    'magic': '\uf0d0',
    'magnet': '\uf076',
    'male': '\uf183',
    'map marker': '\uf041',
    'map o': '\uf278',
    'map pin': '\uf276',
    'map signs': '\uf277',
    'map ': '\uf279',
    'mariadb': '\uf352',
    'markdown': '\uf353',
    'mars double': '\uf227',
    'mars stroke h': '\uf22b',
    'mars stroke': '\uf229',
    'mars stroke v': '\uf22a',
    'mars': '\uf222',
    'mastodon alt': '\uf2e2',
    'mastodon square': '\uf300',
    'mastodon': '\uf2e1',
    'matrix org': '\uf313',
    'maxcdn': '\uf136',
    'meanpath': '\uf20c',
    'medium square': '\uf2f8',
    'medium': '\uf23a',
    'medkit': '\uf0fa',
    'meetup': '\uf2e0',
    'meh o': '\uf11a',
    'mercury': '\uf223',
    'microchip': '\uf2db',
    'microphone slash': '\uf131',
    'microphone': '\uf130',
    'minus circle': '\uf056',
    'minus square o': '\uf147',
    'minus square': '\uf146',
    'minus': '\uf068',
    'mixcloud': '\uf289',
    'mobile': '\uf10b',
    'modx': '\uf285',
    'money': '\uf0d6',
    'moon o': '\uf186',
    'moon': '\uf328',
    'motorcycle': '\uf21c',
    'mouse pointer': '\uf245',
    'music': '\uf001',
    'mysql': '\uf354',
    'neuter': '\uf22c',
    'newspaper o': '\uf1ea',
    'nextcloud square': '\uf307',
    'nextcloud': '\uf306',
    'nodejs': '\uf308',
    'nordcast': '\uf355',
    'object group': '\uf247',
    'object ungroup': '\uf248',
    'odnoklassniki square': '\uf264',
    'odnoklassniki': '\uf263',
    'opencart': '\uf23d',
    'open collective': '\uf336',
    'openid': '\uf19b',
    'opera': '\uf26a',
    'optin monster': '\uf23c',
    'orcid': '\uf337',
    'outdent': '\uf03b',
    'pagelines': '\uf18c',
    'paint brush': '\uf1fc',
    'paperclip': '\uf0c6',
    'paper plane o': '\uf1d9',
    'paper plane': '\uf1d8',
    'paragraph': '\uf1dd',
    'patreon': '\uf2f0',
    'pause circle o': '\uf28c',
    'pause circle': '\uf28b',
    'pause': '\uf04c',
    'paw': '\uf1b0',
    'paypal': '\uf1ed',
    'peertube': '\uf2e4',
    'pencil square o': '\uf044',
    'pencil square': '\uf14b',
    'pencil': '\uf040',
    'percent': '\uf295',
    'phone square': '\uf098',
    'phone': '\uf095',
    'php': '\uf30e',
    'picture o': '\uf03e',
    'pie chart': '\uf200',
    'pinterest p': '\uf231',
    'pinterest square': '\uf0d3',
    'pinterest': '\uf0d2',
    'pixelfed': '\uf314',
    'plane': '\uf072',
    'play circle o': '\uf01d',
    'play circle': '\uf144',
    'play': '\uf04b',
    'pleroma': '\uf324',
    'plug': '\uf1e6',
    'plume': '\uf356',
    'plus circle': '\uf055',
    'plus square o': '\uf196',
    'plus square': '\uf0fe',
    'plus': '\uf067',
    'podcast': '\uf2ce',
    'postgresql': '\uf357',
    'power off': '\uf011',
    'print ': '\uf02f',
    'product hunt': '\uf288',
    'puzzle piece': '\uf12e',
    'python': '\uf322',
    'qq': '\uf1d6',
    'qrcode': '\uf029',
    'question circle o': '\uf29c',
    'question circle': '\uf059',
    'question': '\uf128',
    'quora': '\uf2c4',
    'quote left': '\uf10d',
    'quote right': '\uf10e',
    'random': '\uf074',
    'ravelry': '\uf2d9',
    'react': '\uf302',
    'rebel': '\uf1d0',
    'recycle': '\uf1b8',
    'reddit alien': '\uf281',
    'reddit square': '\uf1a2',
    'reddit': '\uf1a1',
    'refresh': '\uf021',
    'registered': '\uf25d',
    'renren': '\uf18b',
    'repeat': '\uf01e',
    'reply all': '\uf122',
    'reply': '\uf112',
    'researchgate': '\uf338',
    'retweet': '\uf079',
    'road': '\uf018',
    'rocket': '\uf135',
    'rss square': '\uf143',
    'rss': '\uf09e',
    'rub': '\uf158',
    'safari': '\uf267',
    'sass alt': '\uf359',
    'sass': '\uf358',
    'scissors': '\uf0c4',
    'scribd': '\uf28a',
    'scuttlebutt': '\uf2ea',
    'search minus': '\uf010',
    'search plus': '\uf00e',
    'search': '\uf002',
    'sellsy': '\uf213',
    'server': '\uf233',
    'shaarli o': '\uf2f6',
    'shaarli': '\uf2f5',
    'share alt square': '\uf1e1',
    'share alt': '\uf1e0',
    'share square o': '\uf045',
    'share square': '\uf14d',
    'share': '\uf064',
    'shield': '\uf132',
    'ship': '\uf21a',
    'shirtsinbulk': '\uf214',
    'shopping bag': '\uf290',
    'shopping basket': '\uf291',
    'shopping cart': '\uf07a',
    'shower': '\uf2cc',
    'signalapp': '\uf30c',
    'signal': '\uf012',
    'sign in': '\uf090',
    'sign language': '\uf2a7',
    'sign out': '\uf08b',
    'simplybuilt': '\uf215',
    'sitemap': '\uf0e8',
    'skate': '\uf35a',
    'sketchfab': '\uf35b',
    'skyatlas': '\uf216',
    'skype': '\uf17e',
    'slack': '\uf198',
    'sliders': '\uf1de',
    'slideshare': '\uf1e7',
    'smile o': '\uf118',
    'snapchat ghost': '\uf2ac',
    'snapchat square': '\uf2ad',
    'snapchat': '\uf2ab',
    'snowdrift': '\uf2f1',
    'snowflake o': '\uf2dc',
    'social home': '\uf2ec',
    'sort alpha asc': '\uf15d',
    'sort alpha desc': '\uf15e',
    'sort amount asc': '\uf160',
    'sort amount desc': '\uf161',
    'sort asc': '\uf0de',
    'sort desc': '\uf0dd',
    'sort numeric asc': '\uf162',
    'sort numeric desc': '\uf163',
    'sort': '\uf0dc',
    'soundcloud': '\uf1be',
    'space shuttle': '\uf197',
    'spell check': '\uf327',
    'spinner': '\uf110',
    'spoon': '\uf1b1',
    'spotify': '\uf1bc',
    'square o': '\uf096',
    'square': '\uf0c8',
    'stack exchange': '\uf18d',
    'stack overflow': '\uf16c',
    'star half o': '\uf123',
    'star half': '\uf089',
    'star o': '\uf006',
    'star': '\uf005',
    'steam square': '\uf1b7',
    'steam': '\uf1b6',
    'step backward': '\uf048',
    'step forward': '\uf051',
    'stethoscope': '\uf0f1',
    'sticky note o': '\uf24a',
    'sticky note': '\uf249',
    'stop circle o': '\uf28e',
    'stop circle': '\uf28d',
    'stop': '\uf04d',
    'street view': '\uf21d',
    'strikethrough': '\uf0cc',
    'stumbleupon circle': '\uf1a3',
    'stumbleupon': '\uf1a4',
    'subscript': '\uf12c',
    'subway': '\uf239',
    'suitcase': '\uf0f2',
    'sun o': '\uf185',
    'sun': '\uf329',
    'superpowers': '\uf2dd',
    'superscript': '\uf12b',
    'syncthing': '\uf311',
    'tablet': '\uf10a',
    'table': '\uf0ce',
    'tachometer': '\uf0e4',
    'tags': '\uf02c',
    'tag': '\uf02b',
    'tasks': '\uf0ae',
    'taxi': '\uf1ba',
    'telegram': '\uf2c6',
    'television': '\uf26c',
    'tencent weibo': '\uf1d5',
    'terminal': '\uf120',
    'text height': '\uf034',
    'textpattern': '\uf35d',
    'text width': '\uf035',
    'tex': '\uf35c',
    'themeisle': '\uf2b2',
    'thermometer empty': '\uf2cb',
    'thermometer full': '\uf2c7',
    'thermometer half': '\uf2c9',
    'thermometer quarter': '\uf2ca',
    'thermometer three quarters': '\uf2c8',
    'th large': '\uf009',
    'th list': '\uf00b',
    'th': '\uf00a',
    'thumbs down': '\uf165',
    'thumbs o down': '\uf088',
    'thumbs o up': '\uf087',
    'thumbs up': '\uf164',
    'thumb tack': '\uf08d',
    'ticket': '\uf145',
    'times circle o': '\uf05c',
    'times circle': '\uf057',
    'times': '\uf00d',
    'tint': '\uf043',
    'tipeee': '\uf301',
    'toggle off': '\uf204',
    'toggle on': '\uf205',
    'tor onion': '\uf32e',
    'trademark': '\uf25c',
    'train': '\uf238',
    'transgender alt': '\uf225',
    'transgender': '\uf224',
    'trash o': '\uf014',
    'trash': '\uf1f8',
    'tree': '\uf1bb',
    'trello': '\uf181',
    'tripadvisor': '\uf262',
    'trophy': '\uf091',
    'truck': '\uf0d1',
    'try ': '\uf195',
    'tty': '\uf1e4',
    'tumblr square': '\uf174',
    'tumblr': '\uf173',
    'twitch': '\uf1e8',
    'twitter square': '\uf081',
    'twitter': '\uf099',
    'umbrella': '\uf0e9',
    'underline': '\uf0cd',
    'undo': '\uf0e2',
    'unity': '\uf35e',
    'universal access': '\uf29a',
    'university': '\uf19c',
    'unlock alt': '\uf13e',
    'unlock': '\uf09c',
    'unsplash': '\uf325',
    'upload': '\uf093',
    'usb': '\uf287',
    'usd': '\uf155',
    'user circle o': '\uf2be',
    'user circle': '\uf2bd',
    'user md': '\uf0f0',
    'user o': '\uf2c0',
    'user plus': '\uf234',
    'user secret': '\uf21b',
    'users': '\uf0c0',
    'user times': '\uf235',
    'user': '\uf007',
    'venus double': '\uf226',
    'venus mars': '\uf228',
    'venus': '\uf221',
    'viacoin': '\uf237',
    'viadeo square': '\uf2aa',
    'viadeo': '\uf2a9',
    'video camera': '\uf03d',
    'vimeo square': '\uf194',
    'vimeo': '\uf27d',
    'vine': '\uf1ca',
    'vk': '\uf189',
    'volume control phone': '\uf2a0',
    'volume down': '\uf027',
    'volume mute': '\uf32f',
    'volume off': '\uf026',
    'volume up': '\uf028',
    'weibo': '\uf18a',
    'weixin': '\uf1d7',
    'whatsapp': '\uf232',
    'wheelchair alt': '\uf29b',
    'wheelchair': '\uf193',
    'wifi': '\uf1eb',
    'wikidata': '\uf31a',
    'wikipedia w': '\uf266',
    'window close o': '\uf2d4',
    'window close': '\uf2d3',
    'window maximize': '\uf2d0',
    'window minimize': '\uf2d1',
    'window restore': '\uf2d2',
    'windows': '\uf17a',
    'wire': '\uf32c',
    'wordpress': '\uf19a',
    'wpbeginner': '\uf297',
    'wpexplorer': '\uf2de',
    'wpforms': '\uf298',
    'wrench': '\uf0ad',
    'xing square': '\uf169',
    'xing': '\uf168',
    'xmpp': '\uf2f9',
    'yahoo': '\uf19e',
    'y combinator': '\uf23b',
    'yelp': '\uf1e9',
    'yoast': '\uf2b1',
    'youtube play': '\uf16a',
    'youtube square': '\uf166',
    'youtube': '\uf167',
    'zotero': '\uf309 '
}